# Generated by Django 6.0.5 on 2026-05-25 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField(help_text='0-based row number in the source file')),
                ('raw_data', models.JSONField(help_text='Original key-value pairs, keys preserved as-is from source')),
                ('parse_error', models.TextField(blank=True, help_text='Non-empty if this row failed to parse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['row_index'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('fuel', 'Fuel (direct combustion)'), ('procurement', 'Procurement / purchased goods'), ('electricity', 'Grid electricity'), ('flight', 'Air travel'), ('hotel', 'Hotel accommodation'), ('ground_transport', 'Ground transport')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged / needs attention')], default='pending', max_length=20)),
                ('activity_date', models.DateField(help_text='Date of activity (normalized from source)')),
                ('period_start', models.DateField(blank=True, help_text='For billing-period data (utility)', null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('sap_plant_code', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('employee_id', models.CharField(blank=True, help_text='For travel records', max_length=100)),
                ('source_quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('source_unit', models.CharField(help_text='e.g. liters, kWh, MWh, kg, miles', max_length=50)),
                ('quantity_kwh', models.DecimalField(blank=True, decimal_places=4, help_text='Energy in kWh (null for non-energy records)', max_digits=20, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=4, help_text='Distance in km (travel records only)', max_digits=20, null=True)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=8, help_text='kg CO2e per unit (kWh or km)', max_digits=20, null=True)),
                ('emission_factor_source', models.CharField(blank=True, help_text='e.g. UK DESNZ 2024, ICAO, DEFRA', max_length=255)),
                ('quantity_kg_co2e', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated kg CO2e', max_digits=20, null=True)),
                ('source_vendor', models.CharField(blank=True, help_text='Vendor/supplier from SAP', max_length=255)),
                ('source_material_code', models.CharField(blank=True, max_length=100)),
                ('fuel_type', models.CharField(blank=True, help_text='diesel, natural_gas, petrol, etc.', max_length=100)),
                ('utility_meter_id', models.CharField(blank=True, max_length=100)),
                ('travel_origin', models.CharField(blank=True, help_text='IATA airport code', max_length=10)),
                ('travel_destination', models.CharField(blank=True, max_length=10)),
                ('travel_class', models.CharField(blank=True, help_text='economy, business, first', max_length=20)),
                ('flag_reason', models.TextField(blank=True, help_text='Why this row was auto-flagged')),
                ('was_edited', models.BooleanField(default=False, help_text='True if analyst edited any field post-ingestion')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('raw_row', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_record', to='emissions.rawrow')),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('edited', 'Field edited')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('field_changed', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SourceBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel/Procurement'), ('utility', 'Utility/Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_parsed', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('rows_flagged', models.IntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='raw_uploads/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='emissions.client')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='rawrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_rows', to='emissions.sourcebatch'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.sourcebatch'),
        ),
        migrations.CreateModel(
            name='PlantCodeLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_codes', to='emissions.client')),
            ],
            options={
                'unique_together': {('client', 'sap_code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='rawrow',
            unique_together={('batch', 'row_index')},
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['client', 'status'], name='emissions_e_client__a9862c_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['client', 'scope'], name='emissions_e_client__95b7c8_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['batch'], name='emissions_e_batch_i_f2aa5a_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['activity_date'], name='emissions_e_activit_c89ba8_idx'),
        ),
    ]
